### ISSUE TITLE
Installation seems to hang on Windows 11

### ISSUE THREAD

**Issue by uhansla** [BrunnerInnovation/vJoy#1]
I am trying to install Vjoy on my ROG Ally. OS is Windows 11 Home Version 10.0.22631 and the installation seems to hang for me. 

The setup log seems to get stuck after this step

2024-03-17 15:50:50.427   InitFromRegistry() - using the default registry file: vJoyInit.reg
2024-03-17 15:50:50.427   InitFromRegistry(): Default optional registry FileC:\Users\umesh\Downloads\vJoyInit.reg not found, continue without it
2024-03-17 15:50:50.427   Exec_vJoyInstall() - Start

File is attached. Thanks
[Setup Log 2024-03-17 #005.txt](https://github.com/BrunnerInnovation/vJoy/files/14627225/Setup.Log.2024-03-17.005.txt)

**Comment by uhansla** [comment]
Never mind. I went through the process of removing old drivers (using pnputil). I cleared out the old driver and now the install succeeded.

**Comment by jwvanderbeck** [comment]
Any chance adding details to this for others who run into the same problem? Like me :)

**Comment by spaelectronics** [comment]
The install hangs for me too. First time installing vJoy, so I had no previous drivers.

**Comment by retep998** [comment]
Installer hangs for me as well on Windows 11, even when I double checked to make sure I didn't have any old drivers first with pnputil.
